# Generated by Django 4.2.4 on 2023-09-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.CharField(max_length=200),
        ),
    ]
