# Generated by Django 4.2.4 on 2023-09-05 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_jobseeker_date_of_passout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='qulification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='account.qulification'),
        ),
    ]
