# Generated by Django 4.2.4 on 2023-09-15 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('qulification', models.TextField()),
                ('resume', models.FileField(upload_to='')),
                ('status', models.BooleanField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.jobs')),
            ],
        ),
    ]
